[platformio]
src_dir = .

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags = -std=gnu++17
build_src_filter =
  +<d10_button_matrix.c>
  +<d10_can_driver.c>
  +<d10_test.c>
  +<d10_platform.cpp>
